# Generated by Django 4.2.4 on 2023-08-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='geeks_field',
            new_name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='componentType',
            field=models.CharField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
