# Generated by Django 4.2.4 on 2024-09-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='latest_message',
        ),
    ]
