# Generated by Django 4.2.4 on 2024-09-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
