# Generated by Django 4.2.4 on 2024-09-26 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_orders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_account', models.CharField(max_length=100)),
                ('time_of_bought', models.DateTimeField(auto_now_add=True)),
                ('subscription_type', models.CharField(choices=[('HOBBIES', 'Hobbies'), ('PROFESSIONALS', 'Professionals')], max_length=40)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
