# Generated by Django 4.2.4 on 2024-09-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paypal_subscribing_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
