# Generated by Django 4.2.4 on 2024-09-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_subscription_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paypal_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
