# Generated by Django 4.2.4 on 2024-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_subscription_paypal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumeuser',
            name='role',
            field=models.CharField(default='non_subscription_user', max_length=70, null=True),
        ),
    ]
